### PR TITLE
Refactor/source

### PR DESCRIPTION
**Pull request by akalinow**

### CODE REVIEW

**Comment by akalinow** [comment]
Please leave all the elements corresponding to EventSourceMC, ie. makMCTrackTree, etc. We have changed the class behind the EventSourceMC, but the  rest of the application remains unchanged.

**Comment by pSzyc** [comment]
> Please leave all the elements corresponding to EventSourceMC, ie. makMCTrackTree, etc. We have changed the class behind the EventSourceMC, but the rest of the application remains unchanged.

I reverted the comit which deleted `makeMCTrackTree`.

The `makeMCTrackTree` uses some functions of the `EventSourceMC `that are not required by the `EventSourceBase` class.
These are: `getGeneratedTrack` and `getGeneratedEventType`

First method returns a vector of `Track3D`. In MonteCarlo module in `ModuleExchangeSpace` we just have one `Track3D` stored so this method wont be possible to implement without some refactor of `runControllerMC` (`EventSourceGeant4` can easly return one `Track3D`, `makeMCTrackTree` requires 2 different). 
``` 
const Track3D & aTrack3DGenAlpha = myEventSource->getGeneratedTrack(0);

const Track3D & aTrack3DGenCarbon = myEventSource->getGeneratedTrack(1);
``` 
`getGeneratedEventType` on the other hand returns a `pid_type`, but again we dont have this easly in runControllerMC, I just see that `SimEvent` can return `reaction_type` and `EventInfo` has member `eventType` which is `unsigned long` and is converted to `std::bitset<64>`  in `GetEventType` method

**Comment by akalinow** [comment]
Please adapt the makeMCTrackTree to new EventSource, and get the info on generated track from SimEvent.

**Comment by akalinow** [comment]
It seems that  EventSourceGeant4 is still present in the code. If so please rename it to EventSourceMC, so everywhere else the code using MC will be unchanged (module issue with makeTrackTreeMC)

**Comment by pSzyc** [comment]
@akalinow I have renamed Geant4 -> MC. However I have not connected the makeTrackTreeMC with new EventSourceMC. I am not sure where to take from two Track3D corresponding to the alpha particle and carbon atom. I suppose it can be get from SimTracks of SimEvent which can be converted to Track3D. Is that the case?

**Comment by pSzyc** [comment]
I have added a function which generates vector of Track3D from SImTracks of SimEvent. Idk if thats what we wanted (from what I understood these SimTracks are tracks of each particles and in this configuration so it will be Track3D)

**Comment by akalinow** [comment]
Looks good, let's merge.

**Pull request merged**
